### ISSUE TITLE
Hack #1

### ISSUE THREAD

**Issue by iamstuartwilson** [catchdigital/catch-music#1]
# Todo:
- [ ] Connect to local Sonos and read current playing track
- [ ] Send message to slack channel with an attachment format for showing a song name, artist, thumbnail and rate links
- [ ] Create endpoints which saves a like / dislike to a database for a song guid (hooks up to rate links)
- [ ] Create a view which shows a list of songs with ordering (most recent, most liked, most hated)
